const finalTable = {
    "fede": {
        "A" : ["Italy", "Turkey"],
        "B" : ["Belgium", "Denmark"],
        "C" : ["Netherlands", "Austria"],
        "D" : ["England", "Croatia"],
        "E" : ["Spain","Poland"],
        "F" : ["France", "Germany"],
        "terze" : ["Portugal", "Switzerland", "Russia", "Slovakia"],
        "ottavi" :
            ["Italy", "Turkey",
            "Belgium", "Denmark",
            "Netherlands","Austria",
            "England", "Croatia",
            "Spain", "Poland",
            "France", "Germany",
            "Portugal", "Switzerland", "Russia", "Slovakia"],
        "quarti" : ["Croatia", "Italy", "Denmark", "Belgium", "France", "Germany", "Portugal", "Spain"],
        "semi" : ["France", "Belgium", "Portugal", "Germany"],
        "prima" : "Germany",
        "seconda" : "France"
    },
    "gaid" : {
        "A" : ["Italy", "Switzerland"],
        "B" : ["Belgium", "Denmark"],
       "C" : ["Netherlands", "Ukraine"],
       "D" : ["England", "Croatia"],
       "E" : ["Spain","Poland"],
        "F" : ["France", "Portugal"],
       "terze" : ["Austria", "Germany", "Wales", "Russia"],
    "ottavi" :
     ["Italy", "Switzerland",
              "Belgium", "Denmark",
              "Netherlands","Ukraine",
              "England", "Croatia",
              "Spain", "Poland",
              "France", "Portugal ",
              "Austria", "Germany ", "Russia", "Wales"],
  
       "quarti" : ["Croatia", "Italy", "Switzerland", "Belgium", "France", "Germany", "Portugal", "Spain"],
          "semi" : ["France", "Italy", "England", "Germany"],
          "prima" : "France",
          "seconda" : "Germany"  
    },
    "marine": {
        "A" : ["Italy", "Wales"],
        "B" : ["Belgium", "Russia"],
        "C" : ["Ukraine", "Netherlands"],
        "D" : ["England", "Croatia"],
        "E" : ["Poland","Spain"],
        "F" : ["France", "Germany"],
        "terze" : ["Portugal", "Switzerland", "Austria", "CzechRepublic"],
        "ottavi" :
            ["Italy", "Wales",
            "Belgium", "Russia",
            "Ukraine","Netherlands",
            "England", "Croatia",
            "Poland", "Spain",
            "France", "Germany",
            "Portugal", "Switzerland", "Austria", "CzechRepublic"],
        "quarti" : ["Croatia", "Italy", "Wales", "Belgium", "France", "Germany", "Ukraine", "Poland"],
        "semi" : ["France", "Belgium", "Wales", "Germany"],
        "prima" : "Germany",
        "seconda" : "Belgium"
    },
    "nicola": {
        "A" : ["Italy", "Wales"],
        "B" : ["Belgium", "Russia"],
        "C" : ["Netherlands", "Ukraine"],
        "D" : ["England", "Croatia"],
        "E" : ["Spain","Poland"],
        "F" : ["France", "Germany"],
        "terze" : ["Portugal", "Denmark", "Sweden", "Turkey"],
        "ottavi" :
            ["Italy", "Wales",
            "Belgium", "Russia",
            "Netherlands","Ukraine",
            "England", "Croatia",
            "Spain", "Poland",
            "France", "Germany",
            "Portugal", "Denmark", "Sweden", "Turkey"],
        "quarti" : ["Croatia", "France", "Italy", "Belgium", "Wales", "Portugal", "Germany", "Spain"],
        "semi" : ["France", "Italy", "Portugal", "Germany"],
        "prima" : "Italy",
        "seconda" : "Portugal"
    },
    "lollo": {
        "A" : ["Italy", "Switzerland"],
        "B" : ["Belgium", "Denmark"],
        "C" : ["Austria", "Netherlands"],
        "D" : ["England", "Croatia"],
        "E" : ["Spain","Poland"],
        "F" : ["France", "Germany"],
        "terze" : ["Portugal", "Turkey", "Ukraine", "Sweden"],
        "ottavi" :
            ["Italy", "Switzerland",
            "Belgium", "Denmark",
            "Austria","Netherlands",
            "England", "Croatia",
            "Spain", "Poland",
            "France", "Germany",
            "Portugal", "Turkey", "Ukraine", "Sweden"],
        "quarti" : ["Croatia", "Italy", "Denmark", "Belgium", "France", "England", "Portugal", "Spain"],
        "semi" : ["France", "Italy", "Portugal", "England"],
        "prima" : "France",
        "seconda" : "Portugal"
    },

}

module.exports.finalTable = finalTable